ALTER TYPE "BookingKind" ADD VALUE IF NOT EXISTS 'CLASS';
ALTER TYPE "BookingKind" ADD VALUE IF NOT EXISTS 'RENTAL';
ALTER TYPE "BookingKind" ADD VALUE IF NOT EXISTS 'EVENT';
ALTER TYPE "BookingKind" ADD VALUE IF NOT EXISTS 'TABLE';
